### ISSUE TITLE
Profile is not listed in dropdown on which to apply rules

### ISSUE THREAD

**Issue by chaosbuster** [twomice/com.joineryhq.mappins#7]
I have a profile on which I would like to apply the pins that is not listed in the dropdown.  The profile that I was wanting to see in the dropdown and apply the rules, does have the "Enable mapping for this profile" and is currently a directory that I have public to users.  We currently have about 40 profiles in our CiviCRM setup.

**Comment by twomice** [comment]
I think this is because the API call that fetches profiles is defaulting to a limit of 25 items. Should be able to set that to "no limit" and thus list all profiles. Patch forthcoming.

**Comment by twomice** [comment]
@chaosbuster I think I've got a fix for this. Could you try the code in the 7_profiles_not_listed branch? (Downloading from github, eg., https://github.com/twomice/com.joineryhq.mappins/archive/7_profiles_not_listed.zip). It should show as version "0.1-alpha5-branch7" and should resolve the issue. Please let me know your findings.

**Comment by chaosbuster** [comment]
I uninstalled and removed the alpha5 version and installed this new version.  I do see the profile now that I was interested in applying map pins.  Thank you for the patch!   

I am about to head out of town and unable to test fully right now by re-implementing the Rules specifically to this profile.  I will do this test early next week.
